---
Name: lazyloadedimage
---

SilverStripe\Assets\Image:
  extensions:
    - DNADesign\Images\Extensions\LazyloadedImageExtension

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - DNADesign\Images\Extensions\LazyloadedImageExtension
